CREATE TABLE LOG(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    TIME DATE,
    BET NUMERIC(10, 2),
    WIN NUMERIC(10, 2)
);

CREATE TABLE USERS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    EMAIL VARCHAR(50),
    GEO VARCHAR(1000)
);
